# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityCode', models.CharField(max_length=5)),
                ('CityName', models.CharField(max_length=50)),
                ('CityEnName', models.CharField(max_length=50)),
                ('CityLatiude', models.CharField(max_length=50)),
                ('CityLongitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=5)),
                ('CountryName', models.CharField(max_length=100)),
                ('CountryEnName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=50)),
                ('HotelEnName', models.CharField(max_length=50)),
                ('HotelLatiude', models.CharField(max_length=50)),
                ('HotelLongitude', models.CharField(max_length=50)),
                ('HotelMainImage', models.CharField(max_length=50)),
                ('HotelStar', models.CharField(max_length=5)),
                ('HotelCityId', models.CharField(max_length=50)),
                ('HotelCityName', models.CharField(max_length=50)),
                ('HotelCityEnName', models.CharField(max_length=50)),
                ('HotelDescription', models.CharField(max_length=50)),
                ('HotelEnDescription', models.CharField(max_length=50)),
                ('HotelSite', models.CharField(max_length=50)),
                ('HotelTell', models.CharField(max_length=50)),
                ('HotelRules', models.CharField(max_length=50)),
                ('HotelAddress', models.CharField(max_length=50)),
                ('HotelFax', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Country')),
            ],
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SmallGalleryUrl', models.CharField(max_length=200)),
                ('MediumGalleryUrl', models.CharField(max_length=200)),
                ('LargeGalleryUrl', models.CharField(max_length=200)),
                ('ThumbnailGalleryUrl', models.CharField(max_length=200)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceCode', models.CharField(max_length=20)),
                ('ServiceName', models.CharField(max_length=20)),
                ('ServiceEnName', models.CharField(max_length=20)),
                ('ServiceDescription', models.CharField(max_length=20)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Room'),
        ),
        migrations.AddField(
            model_name='hotelgallery',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Room'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Country'),
        ),
    ]
