# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-01 14:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20190401_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='HotelEnDescription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
