# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20190401_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='hotels.HotelOption'),
        ),
    ]
