# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20190403_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='HotelStar',
            field=models.IntegerField(default=0),
        ),
    ]
