# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20190329_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to=b''),
        ),
    ]
