# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20190329_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200)),
                ('iata', models.CharField(max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='time',
            new_name='outband_time',
        ),
        migrations.AddField(
            model_name='tour',
            name='min_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.City'),
        ),
        migrations.AddField(
            model_name='tour',
            name='outband_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='stay_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.TourType'),
        ),
        migrations.AddField(
            model_name='tour',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Airline'),
        ),
    ]
