# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tourhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourhotel',
            name='hotelLink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
