# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 18:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20190404_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(default='22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='documents',
            field=ckeditor.fields.RichTextField(default='22'),
            preserve_default=False,
        ),
    ]
