# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 18:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20190404_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='documents',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
