# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20190404_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='documents',
        ),
    ]
