# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_auto_20190406_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='service',
        ),
        migrations.AddField(
            model_name='tourhotel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.TourService'),
        ),
    ]
