# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityCode', models.CharField(max_length=5)),
                ('CityName', models.CharField(max_length=50)),
                ('CityEnName', models.CharField(max_length=50)),
                ('CityLatiude', models.CharField(max_length=50)),
                ('CityLongitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=5)),
                ('CountryName', models.CharField(max_length=100)),
                ('CountryEnName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Country'),
        ),
    ]
