# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200)),
                ('iata', models.CharField(max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
