# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justoneotherpanelservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.JustOneOtherPanelCategory'),
        ),
        migrations.AddField(
            model_name='justoneotherpanelservice',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.JustOneOtherPanelType'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='api_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.APIAddress'),
        ),
        migrations.AddField(
            model_name='apiaddress',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.APIURL'),
        ),
    ]
