# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
