# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-06 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_subscriber_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code_meli',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
