# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('en_country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('airport', models.CharField(max_length=100)),
                ('iata', models.CharField(max_length=5)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='tickets.Airport')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='tickets.Airport')),
            ],
        ),
    ]
