# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('inf', models.IntegerField()),
                ('request_code', models.IntegerField()),
                ('outband_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outband', to='tickets.Course')),
                ('return_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return+', to='tickets.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
