# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20181203_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='lat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='airport',
            name='lng',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='airport',
            name='order',
            field=models.CharField(max_length=20),
        ),
    ]
