# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20181203_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(),
        ),
    ]
