# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20181203_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='return_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return+', to='tickets.Course'),
        ),
    ]
