# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20181203_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='child',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='inf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='request_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='return_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return+', to='tickets.Course'),
        ),
    ]
