# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20181203_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=5)),
                ('airport_name_fa', models.CharField(max_length=50)),
                ('airport_name_en', models.CharField(max_length=50)),
                ('city_name_fa', models.CharField(max_length=50)),
                ('city_name_en', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baggage_type', models.CharField(max_length=5)),
                ('Quantity', models.IntegerField()),
                ('Unit', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=5)),
                ('flight_class', models.CharField(max_length=5)),
                ('cabin', models.CharField(max_length=5)),
                ('refund', models.CharField(max_length=500)),
                ('operator', models.CharField(max_length=30)),
                ('airline', models.CharField(max_length=5)),
                ('airplane', models.CharField(max_length=50)),
                ('airline_name_fa', models.CharField(max_length=50)),
                ('airline_name_en', models.CharField(max_length=50)),
                ('airline_name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerFare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.BigIntegerField()),
                ('fee', models.BigIntegerField()),
                ('tax', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('discount_percent', models.BigIntegerField()),
                ('currency_code', models.CharField(max_length=5)),
                ('capacity', models.IntegerField()),
                ('flight_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('duration', models.TimeField()),
                ('arrival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='tickets.AirportDate')),
                ('baggages', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.Baggage')),
                ('departure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='tickets.AirportDate')),
                ('flight_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.FlightDetails')),
                ('passenger_fare_adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adult', to='tickets.PassengerFare')),
                ('passenger_fare_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='tickets.PassengerFare')),
                ('passenger_fare_infant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infant', to='tickets.PassengerFare')),
                ('ticket_request_outband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbands', to='tickets.TicketRequest')),
                ('ticket_request_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='tickets.TicketRequest')),
            ],
        ),
    ]
