# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_airportdate_baggage_flightdetails_passengerfare_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportdate',
            name='airport_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airportdate',
            name='airport_name_fa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airportdate',
            name='city_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airportdate',
            name='city_name_fa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airportdate',
            name='country_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
