# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20181203_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='airline',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='airline_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='airline_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='airline_name_fa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='airplane',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='cabin',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='flight_class',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='flight_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='operator',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='refund',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
