# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20181203_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger_fare_adult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adult', to='tickets.PassengerFare'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_fare_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='tickets.PassengerFare'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_fare_infant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infant', to='tickets.PassengerFare'),
        ),
    ]
