# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20181203_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='baggages',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Baggage'),
        ),
    ]
