# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-04 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20181203_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportdate',
            name='time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airportdate',
            name='date',
            field=models.DateField(),
        ),
    ]
