# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20181204_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_type', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('accompanied_by_infant', models.BooleanField(default=False)),
                ('prefix', models.CharField(max_length=5)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('persian_given_name', models.CharField(max_length=50)),
                ('persian_surname', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(max_length=5)),
                ('national_id', models.CharField(max_length=15)),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_id', models.CharField(blank=True, max_length=30, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('doc_issue_country', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Passport'),
        ),
    ]
