# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_bookedticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('en_name', models.CharField(max_length=50)),
                ('iso', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
            ],
        ),
    ]
