# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('en_name', models.CharField(max_length=40)),
                ('iata', models.CharField(max_length=5)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
    ]
