# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_bookedticket_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='flight_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_details', to='tickets.FlightDetails'),
        ),
    ]
