# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20190329_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_request_outband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbands', to='tickets.TicketRequest'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_request_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='tickets.TicketRequest'),
        ),
    ]
