# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20190405_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='outband_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outband', to='tickets.Course'),
        ),
    ]
