# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_bookedticket_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightClassLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FlightClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='flightclassletter',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.FlightClassName'),
        ),
    ]
