# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20190411_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightclassname',
            name='name_fa',
            field=models.CharField(default='ss', max_length=200),
            preserve_default=False,
        ),
    ]
