# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_flightclassname_name_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200)),
            ],
        ),
    ]
