# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_flightoperator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightOperator',
        ),
        migrations.AddField(
            model_name='passenger',
            name='expire_passport',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
