# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 09:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('link', models.URLField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('price', models.IntegerField(default=True)),
                ('created_date', models.DateTimeField()),
                ('valid_date', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdvType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starCount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='adv',
            name='advType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.AdvType'),
        ),
    ]
